/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controle;
import Model.Investidor;

/**
 *
 * @author rafael
 */
public class Menu extends javax.swing.JFrame {
    private String opcao;

    /**
     * Creates new form Menu
     */
    Investidor usuario;
    Controle controle;
    
    public Menu(Investidor usuario) {
        initComponents();
        this.usuario = usuario;
        controle = new Controle(usuario);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblMenu = new javax.swing.JLabel();
        RbtOpcao1 = new javax.swing.JRadioButton();
        RbtOpcao2 = new javax.swing.JRadioButton();
        RbtOpcao4 = new javax.swing.JRadioButton();
        RbtOpcao5 = new javax.swing.JRadioButton();
        RbtOpcao3 = new javax.swing.JRadioButton();
        RbtOpcao7 = new javax.swing.JRadioButton();
        RbtOpcao6 = new javax.swing.JRadioButton();
        RbtOpcao8 = new javax.swing.JRadioButton();
        BtSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblMenu.setText("MENU");

        RbtOpcao1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao1.setText("1. Consultar Saldo");
        RbtOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao1ActionPerformed(evt);
            }
        });

        RbtOpcao2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao2.setText("2. Consultar Extrato");
        RbtOpcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao2ActionPerformed(evt);
            }
        });

        RbtOpcao4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao4.setText("4. Sacar");
        RbtOpcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao4ActionPerformed(evt);
            }
        });

        RbtOpcao5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao5.setText("5. Comprar CriptoMoedas");
        RbtOpcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao5ActionPerformed(evt);
            }
        });

        RbtOpcao3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao3.setText("3. Depositar");
        RbtOpcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao3ActionPerformed(evt);
            }
        });

        RbtOpcao7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao7.setText("7. Atualizar Cotação");
        RbtOpcao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao7ActionPerformed(evt);
            }
        });

        RbtOpcao6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao6.setText("6. Vender CriptoMoedas");
        RbtOpcao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao6ActionPerformed(evt);
            }
        });

        RbtOpcao8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RbtOpcao8.setText("8. Sair");
        RbtOpcao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtOpcao8ActionPerformed(evt);
            }
        });

        BtSelecionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtSelecionar.setText("Selecionar");
        BtSelecionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RbtOpcao8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbtOpcao3)
                            .addComponent(RbtOpcao4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(LblMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RbtOpcao7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbtOpcao5)
                            .addComponent(RbtOpcao6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RbtOpcao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RbtOpcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LblMenu)
                .addGap(40, 40, 40)
                .addComponent(RbtOpcao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbtOpcao7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbtOpcao8)
                    .addComponent(BtSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao1ActionPerformed
        opcao = "Opcao 1";
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);

    }//GEN-LAST:event_RbtOpcao1ActionPerformed

    private void RbtOpcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao2ActionPerformed
        opcao = "Opcao 2";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao2ActionPerformed

    private void RbtOpcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao3ActionPerformed
        opcao = "Opcao 3";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao3ActionPerformed

    private void RbtOpcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao4ActionPerformed
        opcao = "Opcao 4";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao4ActionPerformed

    private void RbtOpcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao5ActionPerformed
        opcao = "Opcao 5";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao5ActionPerformed

    private void RbtOpcao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao6ActionPerformed
        opcao = "Opcao 6";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao7.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao6ActionPerformed

    private void RbtOpcao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao7ActionPerformed
        opcao = "Opcao 7";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao8.setSelected(false);
    }//GEN-LAST:event_RbtOpcao7ActionPerformed

    private void RbtOpcao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtOpcao8ActionPerformed
        opcao = "Opcao 8";
        this.RbtOpcao1.setSelected(false);
        this.RbtOpcao2.setSelected(false);
        this.RbtOpcao3.setSelected(false);
        this.RbtOpcao4.setSelected(false);
        this.RbtOpcao5.setSelected(false);
        this.RbtOpcao6.setSelected(false);
        this.RbtOpcao7.setSelected(false);
    }//GEN-LAST:event_RbtOpcao8ActionPerformed

    private void BtSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSelecionarActionPerformed
        if (opcao.equals("Opcao 1")){
            SenhaSaldo senha = new SenhaSaldo(usuario);
            senha.setVisible(true);
            this.setVisible(false);
        }
        
        if (opcao.equals("Opcao 2")){
            SenhaExtrato senha = new SenhaExtrato(usuario);
            senha.setVisible(true);
            this.setVisible(false);
        }
        
        if (opcao.equals("Opcao 3")){
            Depositar deposito = new Depositar(usuario);
            deposito.setVisible(true);
            this.setVisible(false);
        }
        
        if (opcao.equals("Opcao 4")){
            Sacar saque = new Sacar(controle);
            saque.setVisible(true);
            this.setVisible(false);
        }
        
        if(opcao.equals("Opcao 5")){
            ComprarCriptoMoedas comprar = new ComprarCriptoMoedas(usuario);
            comprar.setVisible(true);
            this.setVisible(false);
        }
        
        if(opcao.equals("Opcao 6")){
            VenderCriptoMoedas vender = new VenderCriptoMoedas(usuario);
            vender.setVisible(true);
            this.setVisible(false);
        }
        
        if(opcao.equals("Opcao 7")){
            AtualizarCotacao atualizar = new AtualizarCotacao(usuario);
            atualizar.setVisible(true);
            this.setVisible(false);
        }
        
        if(opcao.equals("Opcao 8")){
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_BtSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSelecionar;
    private javax.swing.JLabel LblMenu;
    private javax.swing.JRadioButton RbtOpcao1;
    private javax.swing.JRadioButton RbtOpcao2;
    private javax.swing.JRadioButton RbtOpcao3;
    private javax.swing.JRadioButton RbtOpcao4;
    private javax.swing.JRadioButton RbtOpcao5;
    private javax.swing.JRadioButton RbtOpcao6;
    private javax.swing.JRadioButton RbtOpcao7;
    private javax.swing.JRadioButton RbtOpcao8;
    // End of variables declaration//GEN-END:variables
}
